name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@master
      - name: Build the Docker image
        uses: docker build -t fluffos_build ./build
      - name: fluffos
        uses: fluffos/fluffos@master
